### PR TITLE
Reduce Memory to 1.5GB

### PR DESCRIPTION
**Pull request by benoitf**
2GB is too high, it prevent almost any sidecar sidecontainer or development container
Theia container is just to run the IDE

### CODE REVIEW

**Comment by l0rd** [comment]
@benoitf but JDT.ls is still running there right? How can 512MB be enough to have Theia, and TS and Java LS running there?

**Comment by benoitf** [comment]
@l0rd yes it's running there but it shouldn't ! :-)
Also AFAIK if you don't have typescript files, ts server is not launched and if you don't have java files, jdt.ls is not launched.

In any case theia runtime is not to perform any development there, sidecar containers should bring the stuff. Also for example theia runtime may not have npm or yarn commands and theia runtime has not maven for example so pretty useless there.

**Comment by l0rd** [comment]
I am afraid that until JDT.ls lives in Theia container we need at least 1GB for it or we won't be able to use any Java project.

**Comment by benoitf** [comment]
@l0rd what are alternatives ? I don't see why when you do JavaScript/TypeScript development (or other technologies) you should get 2GB memory reserved for Java jdt.ls that prevent you to bring any useful sidecar allowing you to really work.
Have another editor ?

**Comment by benoitf** [comment]
@l0rd BTW I think it's kind of an open issue, how user can specify the memory he wants, per workspace for each plug-in ?
Because some ppl may want to assign more memory than the default one for each container.

**Comment by benoitf** [comment]
here are actions:
I will decrease but not to 512MB, let's say keep it at 1.5GB

but I will create a stack and use workspace attribute to decrease more the memory for some usecase.
So default will consume less memory but still allow to use java projects and for Theia development, a stack or devfile/factory with custom attributes will be used

**Comment by benoitf** [comment]
here are actions:
I will decrease but not to 512MB, let's say keep it at 1.5GB

but I will create a stack and use workspace attribute to decrease more the memory for some usecase.
So default will consume less memory but still allow to use java projects and for Theia development, a stack or devfile/factory with custom attributes will be used

**Comment by benoitf** [comment]
@l0rd PR updated

**Comment by l0rd** [comment]
@benoitf thanks LGTM

**Pull request merged**
